name: BobApp CI/CD

on:
  push:
    branches:
      - feat/github-actions
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run back-end tests
        run: mvn test
        working-directory: ./back

      - name: Run front-end tests
        run: npm test
        working-directory: ./front

